entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: john@doe.com
      storage: acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker: {}
log:
  level: DEBUG
api:
  dashboard: true
