services:
  frontend:
    build: frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend-localhost.traefik.me`)" # academy-142-132-228-124.traefik.me
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"
    depends_on:
      - backend
  backend:
    build: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend-localhost.traefik.me`) && PathPrefix (`/api/`)" #academy-142-132-228-124.traefik.me
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik"
    depends_on:
      - database

  database:
    image: mysql/mysql-server:8.0.23
    ports:
      - "3306:3306"
    env_file:
      - environment/database.env
    volumes:
      - ./sqlscripts:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    restart: unless-stopped

volumes:
  dbdata:

networks:
  default:
    external: true
    name: traefik
