services:
  jenkins:
    image: jenkins/jenkins:jdk17
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ssh:/home/jenkins/.ssh
      - jenkins-data:/var/jenkins_home
    labels:
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.daandc.me`)"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.jenkins.tls=true"
      - "traefik.http.routers.jenkins.tls.certresolver=letsencrypt"
      - "traefik.http.routers.jenkins.entrypoints=websecure"

volumes:
  jenkins-data:

networks:
  default:
    external: true
    name: traefik
